# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5ba8ee85188c1ec2638a92e2debed9f065c48bfa04060b37eb9e904509171d483db3f371c4ff9f4eda3a51142ea36ca1fedfda6f5b6c4b1ce7b6a1d55a5380

test:
  secret_key_base: 693162b946d99e34ebbfe15a109111bbfa2db9315fbae5f81ce9a45f33c303188cef5f147220c2c494fc46dc75cd19ad2e720be83dcbad9b5b3a3394b9be1076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
